export default {
    Trade: {
        bgColor: '#191e26',
        shadowColor: '#31363f',
        titleColor: '#262a34',
        Header: {
            navBorderColor: '#31363f',
            navBGColor: '#191e26',
            navItemTextColor: '#d2d4d6',
            navItemUnderlineColor: '#fff',
            navSelectedItemTextColor: '#fff',
            timeZoneTimeTextColor: '#d2d4d6',
            timeZoneDateTextColor: '#76787e',
            nameTextColor: '#fff',
            menuItemLine: '#262a34',
            dropdownBGColor: '#191e26',
            dropdownSelectedBGColor: '#262a34',
            dropdownTextColor: '#92949a',
            dropdownSelectedTextColor: '#fff',
            loginTextColor: '#92949a',
            arrowDown: require("@webExchangeImgs/trade/dark-arrowDown.png"),
            arrowUp: require("@webExchangeImgs/trade/dark-arrowUp.png"),
            arrowRight: require("@webExchangeImgs/trade/dark-arrowRight.png"),
            darkIcon: require("@webExchangeImgs/trade/dark.png"),
            darkActiveIcon: require("@webExchangeImgs/trade/dark-active.png"),
            lightIcon: require("@webExchangeImgs/trade/light.png"),
            lightActiveIcon: require("@webExchangeImgs/trade/light-active.png"),
            avatarIcon: require("@webExchangeImgs/trade/dark-avatar.png"),
            avatarActiveIcon: require("@webExchangeImgs/trade/dark-avatar-active.png"),
            scrollbarThumbColor: '#484c52',
            scrollbarTrackColor: '#32363e'
        },
        Market: {
            arrowDown: require("@webExchangeImgs/trade/dark-arrowDown.png"),
            arrowUp: require("@webExchangeImgs/trade/dark-arrowUp.png"),
            favorite: require("@webExchangeImgs/trade/dark-favorite.png"),
            favoriteHover: require("@webExchangeImgs/trade/dark-favorite-hover.png"),
            favoriteActive: require("@webExchangeImgs/trade/dark-favorite-active.png"),
            curInstrumentTextColor: '#fff',
            titleTextColor: '#92949a',
            contentTextColor: '#d2d4d6',
            upTextColor: constants.themeColors.mode2.green,
            downTextColor: constants.themeColors.mode2.red,
            instrumentsListBoxBorderColor: '#32363e',
            instrumentListBoxBG: '#191e26',
            tabNavTextColor: 'rgba(255, 255, 255, 0.5)',
            tabNavSelectedTextColor: 'rgba(255, 255, 255, 1)',
            tabNavUnderlineColor: 'rgba(255, 255, 255, 0.5)',
            tabNavSelectedUnderlineColor: '#fff',
            searchBoxBGColor: '#191e26',
            searchBGColor: '#262a34',
            searchBorderColor: '#32363e',
            instrumentDetailsTitleBGColor: '#262a34',
            instrumentDetailsTitleBorderColor: '#32363e',
            instrumentDetailsTitleColor: 'rgba(255, 255, 255, 0.5)',
            contentBoxTextColor: 'rgba(255, 255, 255, 0.8)',
            eachLineBGColor: '#252a33',
            scrollbarThumbColor: '#484c52',
            scrollbarTrackColor: '#32363e'
        },
        OrderBook: {
            titleTextColor: '#fff',
            panelIconSplit: require("@webExchangeImgs/trade/dark-split.png"),
            panelIconSplitActive: require("@webExchangeImgs/trade/dark-split-active.png"),
            panelIconBuy: require("@webExchangeImgs/trade/dark-buy.png"),
            panelIconBuyActive: require("@webExchangeImgs/trade/dark-buy-active.png"),            
            panelIconSell: require("@webExchangeImgs/trade/dark-sell.png"),
            panelIconSellActive: require("@webExchangeImgs/trade/dark-sell-active.png"),
            orderTitleTextColor: '#92949a',
            orderTitleBGColor: '#262a34',
            orderTitleBorderColor: '#32363e',
            sellTextFullColor: constants.themeColors.mode2.red,
            sellBGColor: '#2b242c',
            buyTextFullColor: constants.themeColors.mode2.green,
            buyBGColor: '#1f2d2a',
            commTextFullColor: '#fff',
            decimalsTextColor: '#d2d4d6',
            decimalsNumTextColor: '#fff',
            decimalsIconBorderColor: '#32363e',
            scrollbarThumbColor: '#484c52',
            scrollbarTrackColor: '#32363e'
        },
        TradeHistory: {
            titleTextColor: '#fff',
            historyTitleTextColor: '#92949a',
            historyTitleBGColor: '#262a34',
            historyTitleBorderColor: '#32363e',
            sellTextFullColor: constants.themeColors.mode2.red,
            sellBGColor: '#2b242c',
            buyTextFullColor: constants.themeColors.mode2.green,
            buyBGColor: '#1f2d2a',
            commTextFullColor: '#fff',
            scrollbarThumbColor: '#484c52',
            scrollbarTrackColor: '#32363e'
        },
        MyOrder: {
            myOrderTableHeaderBG: '#262a34',
            myOrderTableBodyBGColor: '#191e26',
            myOrderTableBodyHoverBGColor: '#262a34',
            myOrderTableHeaderLineColor: '#32363e',
            tabNavTextColor: 'rgba(255, 255, 255, 0.5)',
            tabNavSelectedTextColor: 'rgba(255, 255, 255, 1)',
            tabNavUnderlineColor: '#32363e',
            tabNavSelectedUnderlineColor: '#fff',
            opsBGColor: '#262a34',
            opsBorderColor: '#32363e',
            opsTextColor: '#d2d4d6',
            viewMoreTextColor: '#d2d4d6',
            arrowDown: require("@webExchangeImgs/trade/dark-arrowDown.png"),
            arrowUp: require("@webExchangeImgs/trade/dark-arrowUp.png"),
            showSelectdTypeBGColor: '#32363e',
            selectedTypeTextColor: '#92949a',
            selectedTypeTextActiveColor: '#fff',
            buyTextColor: constants.themeColors.mode2.green,
            sellTextColor: constants.themeColors.mode2.red,
            cancelBtnColor: '#fff',
            cancelBtnBorderColor: '#fff',
            scrollbarThumbColor: '#484c52',
            scrollbarTrackColor: '#32363e'
        },
        Chart: {
            upColor: constants.themeColors.mode2.red,
            downColor: constants.themeColors.mode2.green,
            volumeUpColor: constants.themeColors.mode2.redShadow,
            volumeDownColor: constants.themeColors.mode2.greenShadow,
            textColor: 'rgba(255, 255, 255, 0.36)',
            lineColor: '#32363e',
            actionBtnColor: '#92949a',
            actionBgColor: '#191e26',
            actionSelectedBtnColor: '#fff',
            actionSelectedBgColor: '#252a33',
            actionDropdownTextColor: '#92949a',
            actionDropdownBgColor: '#191e26',
            actionArrowDown: require("@webExchangeImgs/trade/dark-arrowDown.png"),
            actionArrowUp: require("@webExchangeImgs/trade/dark-arrowUp.png"),
            actionFullScreen: require("@webExchangeImgs/trade/dark-fullscreen.png"),
            actionFullScreenActive: require("@webExchangeImgs/trade/dark-fullscreen-active.png"),
            actionMinScreen: require("@webExchangeImgs/trade/dark-minscreen.png"),
            actionMinScreenActive: require("@webExchangeImgs/trade/dark-minscreen-active.png"),
            depthBgColor: '#191e26',
            depthTextColor: 'rgba(255, 255, 255, 0.45)',
            depthBuyColor: '#1f2d2a',
            depthBuyBorderColor: constants.themeColors.mode2.green,
            depthSellColor: '#2b242c',
            depthSellBorderColor: constants.themeColors.mode2.red,
            depthBorderColor: '#32363e',
            depthTooltipBgColor: '#262a34',
            depthTooltipTitColor: '#fff',
            depthTooltipTextColor: '#92949a',
            depthTooltipBuyColor: constants.themeColors.mode2.green,
            depthTooltipSellColor: constants.themeColors.mode2.red
        },
        BuyOrSell: {
            textColor: '#92949a',
            inputLabelColor: '#92949a',
            titleColor: '#fff',
            activeTextColor: '#fff',
            boxShadow: '#32363e',
            headerBgColor: '#262a34',
            headerFeesIcon: require("@webExchangeImgs/trade/dark-feeIcon.png"),
            headerFeesIconActive: require("@webExchangeImgs/trade/dark-feeIcon-active.png"),
            contentBgColor: '#262a34',
            contentBuyColor: constants.themeColors.mode2.green,
            contentSellColor: constants.themeColors.mode2.red,
            contentTabTextColor: '#76787e',
            contentTabSelectedTextColor: '#fff',
            contentTabSelectedBorderColor: '#fff',
            contentInputTextColor: '#fff',
            contentInputBgColor: '#262a34',
            contentInputLimitValueBgColor: '#262a34',
            contentInputBorderColor: '#32363e',
            contentInputFocusBorderColor: '#fff',
            contentInputDisabledTextColor: '#484c52',
            contentInputDisabledBgColor: '#32363e',
            btnActiveColor: '#fff',
            tabSelectBgColor: '#060b17',
            tabSelectBorderColor: '#262a34',
            tabSelectTextColor: '#92949a',
            tabSelectedTextColor: '#fff',
            tabSelectedBgColor: '#1a1f2a',
            feesDetailBorderColor: '#32363e',
            feesDetailBgColor: '#191e26',
            feesDetailTextColor: '#d2d4d6',
            feesDetailBtnColor: '#fff',
            orderAgingTitColor: '#484c52',
            orderAgingBorderColor: '#242833'
        },
        Modal: {
            bgColor: 'rgba(25, 30, 38, 0.5)',
            textColor: '#fff',
            registerBtnColor: '#00a0d2'
        }
    },
    Primary: {
        Button: {
            blueDefaultColor: '#00a0d2',
            blueHoverColor: '#0092c0',
            bluePressedColor: '#0086b1',
            greenDefaultColor: constants.themeColors.mode2.green,
            greenHoverColor: '#56a547',
            greenPressedColor: '#4e9741',
            redDefaultColor: constants.themeColors.mode2.red,
            redHoverColor: '#ce525e',
            redPressedColor: '#bb4b55'
        }
    }
}